### ISSUE TITLE
USER STORY: As a user I should find a clean and intuitive design and navigate the site easily.

### ISSUE THREAD

**Issue by RubemJanoni** [RubemJanoni/project-PP4#6]
EPIC:<DESIGN>

As a user I should find a clean and intuitive design and navigate the site easily.

**Acceptance Criteria**

- [ ] The design must be clean, minimalist and intuitive, providing the user with pleasant navigation.
- [ ] The design must follow a standard for all pages.

**Tasks**

- [ ] Create a standard template for all sections of the website.
